name: Build Multi-arch Docker Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag (e.g., latest)'
        required: true
        default: 'latest'

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Multi-arch Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: jiangnan24/azure-panel:${{ github.event.inputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
